#ifndef MLIR_CONVERSION_CONVERTTOMTDSP_CONVERTTOMTDSPPASS_H_
#define MLIR_CONVERSION_CONVERTTOMTDSP_CONVERTTOMTDSPPASS_H_

#include <memory>

namespace mlir {

class Pass;

std::unique_ptr<::mlir::Pass> createConvertToMTDSPPass();
}

#endif // MLIR_CONVERSION_CONVERTTOMTDSP_CONVERTTOMTDSPPASS_H_